apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: quiz
  labels:
    app: frontend
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: s3-access-sa 
      containers:
      - name: frontend
        image: rakshithgt96/reactjs-quiz-frontend:1.0.0-11
        env:
        - name: VITE_REACT_APP_API_URL
          value: "http://www.gan2.xyz/api/questions"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: quiz
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    protocol: TCP
  type: ClusterIP
